--DROP TABLE IF EXISTS user;
CREATE TABLE IF NOT EXISTS post
(
  id IDENTITY PRIMARY  KEY,
  title VARCHAR(255) NULL,
  content VARCHAR(1000) NULL,
  create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  modify_at TIMESTAMP NULL
);
